language: node_js
node_js:
- '8'
- '9'
cache: yarn
env:
  global:
    secure: RFUh5CQ6BEvRRc+gMUIsa7Tjjv5gUGVg4r1dKL9eOIhuDbZsU6S3XijBCXc42l+z7XR4jHVdkUHdnGWcFKtnqqB5Te7i3kAZCnuJ5/A6vMrGGEyPobHVkWpEPbe00wUGS3rtkKyXXzvA/yw/5NuG5zttdUOR2XQmS1M8D6V4q1Z+thu/8cCQh/4wWzV7tll/jTv6Kc2XQw+C8q2SRpYGHmC6wWiWxA21PwFdyvh2l3g36bdsrql2wBxTAiaiFKJ8CwoUmW5xFA2mCj/5dfTR2yTJoWl+HMdu8Uj8p4z0SSzgf6U+hreQoTyk0H6ygBNRaNiyvtI1ehlXNxT3t1ps6FNitHarStXf5YiNzWpYkOJ3aydT7HnF6/LDdfYtskUkCX0uiep24xHHrp8X2gawJtunMvVbtXtACKPQTYeLFB+PYpEYq++iKu/GsRBO6t3o4aQj41b1hX5LAj9BKkzP0puP+yJoA0kW9A7x8ZpOIi8/U15vPP/xLJHNTgZf5tTYJyChTgx7J5LZh0bjIICZKVkCbIEdrbG2NT2WiC6YM8SdasCkDR8W3ywCkBdhmj56hPQiAYCGh2chwSkLqGyuDD7OZguuXaoV+kw5/JfSJzrBqHGxqTDDdS+ThSpfY51jyXVrGQpB10qG+eaUPrWMKFJLoxzbkTUmahElQ7P/jKk=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  api_key:
    secure: cm77IHMapO9xHSwiWi6jR1ddYVi6ia9SOC5Ieqqj7qmHS8FzIBGPUazLhc5Yt1TSYtETCruIhNaxKxHruh7m7SkRW7e+tRiDoI3Lc472TPuFJNOTC91yimvk6TgwBTrGdSu04cnStjU8TEviWpqBrviGAGe3ws5v/IrxNA9xV8DKlrPZYQ5SWhWVVudcu63ujXVhMrDMLHPXzXr7vwGvuU0TlTy7Tg6p/ZYzBdJcQ8FNwTHPfh/Rd8p+MwCztgex/X1+EoVR16FMHc8TN3sfvBorVdGsr2cmwhoKYy1hQhVvoKb37P2SceLal4FXsWpncZe92Sx06dbX0iSfCJPrKYL0h4Ef9wahyzZpGBa6CJ5VpDB00sP79Hn6CyOXhxukQAuDFEGhjfXo0p6Zi7Qrk5eHABN5GwEgC2BhHfBXW31TMHtt8WrfzDT2awIO3K3qG8f6nWQSqXG60IhQp5LwL1XTIvMtos9kFSmQb91siddDFClvD40Gb66vtkkO1HZa0lXDP41rnCiilVufXy0RKe0DV0VF5LA6ats8bJtKA+3Rs95SmV3fBq1TDK57w36/6C/RMK2eROotvT5JDzG8t9GO0D0eGD62x8AWUp/P4u5D/aPPQ2LZAWQSaBaI+9jSq3jT1yU1wgVMe9pc6ok8JZyLxw2IQxaTgvN82c14gr4=
  on:
    tags: true
    repo: actano/borders
    node: '8'
